### ISSUE TITLE
Failed to import asset

### ISSUE THREAD

**Issue by sashaouellet** [sashaouellet/Helix#3]
**Describe the bug**
File path translation error occurs when importing any files for a new asset

**To Reproduce**
1. Go to File > Import asset...
2. Choose a folder, set a name for the asset, click import

**Expected behavior**
Should import the files and translate paths properly to achieve that

**Stacktrace**
`Traceback (most recent call last):
  File "/home/souell20/mount/stuhome/Helix/Helix-dev/python/helix/api/commands.py", line 750, in handleInput
    return main(cmd, argv[1:])
  File "/home/souell20/mount/stuhome/Helix/Helix-dev/python/helix/api/commands.py", line 614, in main
    return importEl(**args)
  File "/home/souell20/mount/stuhome/Helix/Helix-dev/python/helix/environment/permissions.py", line 194, in wrapper
    return function(*args, **kwargs)
  File "/home/souell20/mount/stuhome/Helix/Helix-dev/python/helix/api/commands.py", line 235, in importEl
    el = Element(name, elType, show=env.getEnvironment('show'), sequence=sequence, shot=shot, clipName=clipName, makeDirs=True)
  File "/home/souell20/mount/stuhome/Helix/Helix-dev/python/helix/database/element.py", line 202, in __init__
    os.makedirs(self.work_path)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/i-drive/Savannah'
`

**Comment by sashaouellet** [comment]
This was actually remnants of an old bug that created paths incorrectly. Closing.
